image: python:3.7
stages:
  - deploy

deploy_to_dev:
  stage: deploy
  script:
    - /bin/sh -c 'git clone -b stable --depth=1 https://gitlab+deploy-token-155341:xWz-bGxYnvTLcZCzsHEG@gitlab.com/pencillabs/infraestructure/core.git'
    - cd core
    - bin/pencilctl build ejdashboard -i airflow -e dev -c prod --no-cache && bin/pencilctl push ejdashboard -i airflow -e dev -c prod
  tags:
    - osf
  only:
    refs:
      - master
