image: python:3.7
stages:
  - prepare
  - deploy

install_dependencies:
  stage: prepare
  script:
    - apt update && apt install -y bash git
  tags:
    - osf

deploy_to_dev:
  stage: deploy
  script:
    - /bin/sh -c 'git clone -b stable --depth=1 https://gitlab+deploy-token-155341:xWz-bGxYnvTLcZCzsHEG@gitlab.com/pencillabs/infraestructure/core.git'
    - cd core
    # TODO: remove this after issue https://gitlab.com/pencillabs/infraestructure/core/-/issues/227 is done
    - 'sed -i "s#current: local#current: prod#" pencilctl/config.yml'
    - bin/pencilctl build ejdashboard -i airflow -e dev -b master --no-cache && bin/pencilctl push ejdashboard -i airflow -e dev -b master
  tags:
    - osf
  only:
    refs:
      - master
