FROM python:3.7
COPY src /home/airflow/dags/src/
RUN cp /home/airflow/dags/src/.analyticsreporting.dat /home/airflow/
WORKDIR  /home/airflow/dags/src/ej
RUN cp client_secrets.json /tmp/
RUN cp .*.env /tmp
RUN pip install -r requirements.txt
RUN airflow initdb
