version: '3.3'

services:
  jupyter:
    image: jupyter/datascience-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./src:/home/jovyan/work/
      - analysisdata:/tmp/airflow/
  airflow:
    build:
      context: ./
      dockerfile: Dockerfile-airflow
    environment:
      - AIRFLOW_ENV=prod
      - AIRFLOW_HOME=/home/airflow
    volumes:
      - ./src:/home/airflow/dags/src/
      - analysisdata:/tmp/
      - airflowdata:/home/airflow/
    ports:
      - "8080:8080"
    entrypoint: "sh /home/airflow/dags/src/ej/airflow-run.sh" 
volumes:
  analysisdata:
  airflowdata:
